Repository BatiBati/HomeWork, pull requests merged in 2025-09, with the labels that each got.

#14 saved files push
  back/.env
  back/src/controllers/homework/get-my-homeworks.ts
  back/src/controllers/homework/update-homework.ts
  back/src/controllers/student/create-student.ts
  back/src/controllers/student/index.ts
  back/src/controllers/student/refresh-token.ts
  back/src/middleware/auth.stud.middleware.ts
  back/src/models/homework.models.ts
Labels: pinequest, backned, student

#28 student page
  front/src/app/student/[name]/page.tsx
  front/src/app/student/[name]/task/[taskId]/page.tsx
  front/src/app/student/page.tsx
Labels: frontend, pinequest, parent, student, tasks

#33 front build bug fixed
  front/src/app/student/[name]/page.tsx
  front/src/app/student/page.tsx
  front/src/app/teacher/_components/add-task.tsx
Labels: bug, frontend

#37 student page api connection
  front/src/app/student/page.tsx
Labels: frontend, pinequest, backned, homework

#39 backend get student
  back/src/controllers/student/get-student.ts
  back/src/controllers/student/index.ts
  back/src/routers/student.route.ts
Labels: backned, student

#45 teacher model fix
  back/src/controllers/teacher/get-teacher.ts
  back/src/controllers/teacher/login-teacher.ts
  back/src/routers/teacher.route.ts
Labels: backned

#50 backend parent email nemsen
  back/src/models/student.model.ts
Labels: pinequest, parent, backned, student

#57 bagsh task nemhed etseg ehed notification ochno
  back/.env
  back/package-lock.json
  back/package.json
  back/src/controllers/task/create-task.ts
  back/src/utils/mail-handler.ts
  back/yarn.lock
Labels: pinequest, parent, backned, student, teacher

#58 add task fix
  front/src/app/teacher/_components/add-task.tsx
Labels: bug

#60 build fix
  back/src/controllers/task/create-task.ts
  front/src/app/teacher/_components/add-task.tsx
Labels: bug

#65 task teacherIdtai bolsn teacherin id gaar task duuddag bolsn
  back/src/controllers/task/create-task.ts
  back/src/controllers/task/getTaksbyTeacherId.ts
  back/src/routers/task.route.ts
  front/package-lock.json
  front/package.json
  front/src/components/student/studentBody.tsx
  front/src/components/ui/badge.tsx
Labels: backned, tasks

#72 parent email avdag bolson
  front/src/components/student/studentHeader.tsx
  front/src/provider/AuthProvider.tsx
Labels: frontend, pinequest, parent, student

#73 zurag
  front/src/app/page.tsx
Labels: frontend

#75 74 frontendstudentPareninput
  front/src/components/student/studentBody.tsx
  front/src/components/student/studentHeader.tsx
Labels: frontend, pinequest, student

#77 suuld nemegdsen hicheel hamgiin ehend haragdana
  front/src/components/student/studentBody.tsx
  front/src/components/student/studentHeader.tsx
Labels: frontend, student, tasks

#86 Login Design changed
  back/package.json
  back/src/models/user.model.ts
Labels: enhancement, frontend, homework, Login

#89 parent homepage
  front/src/app/student/[id]/page.tsx
  front/src/components/student/studentBody.tsx
  front/src/components/student/studentHeader.tsx
  package-lock.json
Labels: frontend

#91 User model and controller changed
  back/src/controllers/auth/get-me.ts
  back/src/controllers/auth/login.ts
  back/src/controllers/schoolTeacher/create-school-teacher.ts
  back/src/controllers/schoolTeacher/get-school-teacher.ts
  back/src/controllers/schoolTeacher/index.ts
  back/src/controllers/schoolTeacher/update-school-teacher.ts
  back/src/controllers/user/create-user.ts
  back/src/controllers/user/get-user-email.ts
  back/src/controllers/user/get-user-id.ts
  back/src/controllers/user/get-user.ts
  back/src/controllers/user/get-users.ts
  back/src/controllers/user/index.ts
  back/src/controllers/user/update-user.ts
  back/src/middleware/auth.middleware.ts
  back/src/models/school-teacher.model.ts
  back/src/models/user.model.ts
  back/src/routers/user.route.ts
  front/src/app/(private)/parents/page.tsx
  front/src/app/(private)/teacher/_components/add-student.tsx
  front/src/app/(private)/teacher/_components/add-task.tsx
  front/src/app/(private)/teacher/page.tsx
  front/src/app/(public)/page.tsx
  front/src/components/Types/Types.tsx
  front/src/components/loginForm/LoginForm.tsx
  front/src/provider/AuthProvider.tsx
Labels: enhancement, backend, homework, controller, user

#97 Assignment controller, dayCares controller, models routes done
  back/api/index.ts
  back/package-lock.json
  back/src/controllers/assignment/create-assignment.ts
  back/src/controllers/assignment/get-assignments.ts
  back/src/controllers/assignment/index.ts
  back/src/controllers/assignment/update-assignment.ts
  back/src/controllers/children/create-children.ts
  back/src/controllers/children/get-all-childrens.ts
  back/src/controllers/children/get-children-id.ts
  back/src/controllers/children/update-children-id.ts
  back/src/controllers/dayCares/create-daycare.ts
  back/src/controllers/dayCares/get-dayCare.ts
  back/src/controllers/dayCares/index.ts
  back/src/controllers/dayCares/update-daycare.ts
  back/src/controllers/message/get-message.ts
  back/src/controllers/message/index.ts
  back/src/controllers/message/send-message.ts
  back/src/controllers/schoolTeacher/create-school-teacher.ts
  back/src/controllers/schoolTeacher/get-school-teacher.ts
  back/src/controllers/schoolTeacher/index.ts
  back/src/controllers/schoolTeacher/update-school-teacher.ts
  back/src/controllers/task/create-task.ts
  back/src/index.ts
  back/src/models/assignment.models.ts
  back/src/models/children.models.ts
  back/src/models/comment.models.ts
  back/src/models/day-care.models.ts
  back/src/models/message.models.ts
  back/src/routers/assignment.route.ts
  back/src/routers/daycare.route.ts
  back/src/routers/message.route.ts
  back/src/routers/task.route.ts
  back/src/utils/mail-handler.ts
  back/yarn.lock
Labels: enhancement, parent, backend, student, homework, controller, user

#102 bnotification
  back/src/controllers/assignment/create-assignment.ts
  back/src/models/assignment.models.ts
  back/src/models/user.model.ts
  back/src/utils/mail-handler.ts
Labels: pinequest, backend, student, notification

#116 teacher assignment nemdeg bolson
  back/src/controllers/assignment/create-assignment.ts
  back/src/models/assignment.models.ts
  back/src/utils/mail-handler.ts
  front/src/app/(private)/teacher/_components/add-task.tsx
  front/src/app/(private)/teacher/page.tsx
Labels: bug, pinequest, backend, lesson, tasks, children

#118 Front end Parent can watch their childrens assignment
  back/src/controllers/assignment/get-assignments.ts
  back/src/controllers/auth/get-me.ts
  back/src/routers/assignment.route.ts
  back/src/routers/user.route.ts
  front/src/app/(private)/parents/_components/Contents.tsx
  front/src/app/(private)/parents/_components/SidebarParent.tsx
  front/src/app/(private)/parents/page.tsx
  front/src/app/layout.tsx
  front/src/components/loginForm/LoginForm.tsx
  front/src/components/svg/LoadingSvg.tsx
Labels: enhancement, frontend, parent, parents

#123 back end create student bug fixed
  back/src/controllers/children/create-children.ts
  back/src/models/children.models.ts
  front/src/app/(private)/parents/_components/SidebarParent.tsx
Labels: bug, backend

#128 task uusgehed tuhain udur uusgesen daalgavar baih ym bol aldaa zaadag…
  front/src/app/(private)/teacher/_components/add-task.tsx
  front/src/app/(private)/teacher/page.tsx
Labels: frontend, pinequest, teacher, tasks

#148 get assigment by id
  back/src/controllers/assignment/get-assignment-by-id.ts
  back/src/controllers/assignment/index.ts
  back/src/routers/assignment.route.ts
Labels: backend, tasks

#152 id gaar awdag assigment ajildag bolsn
  front/src/app/assignment/[id]/page.tsx
Labels: frontend, tasks

#162 add student done
  back/src/controllers/student/create-student.ts
  front/src/app/(private)/teacher/_components/add-student.tsx
Labels: frontend

#164 build error fixed
  front/src/app/(private)/teacher/_components/add-student.tsx
Labels: bug

#167 P
  back/src/utils/edit.mail.ts
  back/src/utils/mail-handler.ts
  front/src/app/(private)/teacher/_components/assignments-list.tsx
Labels: backend

#170 ParentChat path changed
  front/src/app/(private)/parents/_components/Chat/ChatForSidebar.tsx
  front/src/app/(private)/parents/_components/Contents.tsx
  front/src/app/(private)/parents/_components/Sidebar.tsx
  front/src/app/(private)/parents/page.tsx
Labels: enhancement, frontend, parent, parents

#172 notification css
  back/src/utils/mail-handler.ts
Labels: backend

#232 accordion bug fixed
  front/src/app/(private)/parents/_components/children/ChildrenDataCard.tsx
Labels: bug

#235 copy link svg
  front/src/components/svg/CopyLink.tsx
Labels: frontend

#240 Create user model bug fixed
  back/src/models/user.model.ts
Labels: bug, backend

#243 238 fe add studdent
  back/src/controllers/assignment/update-assignment.ts
  back/src/controllers/user/create-user.ts
  front/src/app/(private)/teacher/_components/add-student.tsx
  front/src/app/(private)/teacher/page.tsx
  front/src/components/loginForm/LoginForm.tsx
Labels: frontend, pinequest, parent, student

#246 map reverse
  front/src/app/(private)/teacher/_components/assignments-list.tsx
Labels: design
